# Generated by Django 4.2.4 on 2023-09-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('department', models.CharField(max_length=255)),
                ('doctor', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
