# Generated by Django 4.2.4 on 2023-09-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaatientNID', models.IntegerField()),
                ('PatientName', models.CharField(max_length=255)),
                ('PatientAge', models.IntegerField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('DiseaseType', models.CharField(max_length=100)),
                ('Medication', models.CharField(max_length=1000)),
            ],
        ),
    ]
