# Generated by Django 4.2.4 on 2023-09-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditech', '0002_newmedication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newmedication',
            old_name='PaatientNID',
            new_name='PatientNID',
        ),
    ]
